{
 "title": "Heizung",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "room",
    "label": "Room",
    "query": "label_values(tado_temperature_set_celsius, zone_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Außen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "tado_temperature_outside_celsius",
     "legendFormat": "Außentemperatur"
    },
    {
     "expr": "tado_solar_intensity_percentage",
     "legendFormat": "Sonnenintensität"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tado_is_zone_powered", "legendFormat": "{{zone_name}}" }
   ]
  },
  {
   "title": "$room",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "repeat": "room",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "tado_temperature_set_celsius{zone_name=\"$room\"}",
     "legendFormat": "Eingestellt"
    },
    {
     "expr": "tado_temperature_measured_celsius{zone_name=\"$room\"}",
     "legendFormat": "Aktuell"
    },
    {
     "expr": "tado_heating_power_percentage{zone_name=\"$room\"}",
     "legendFormat": "Heizleistung"
    },
    {
     "expr": "tado_humidity_measured_percentage{zone_name=\"$room\"}",
     "legendFormat": "Luftfeuchtigkeit"
    },
    {
     "expr": "tado_is_window_open{zone_name=\"$room\"} * 111 - 1",
     "legendFormat": "Fenster offen"
    }
   ]
  }
 ]
}