name: Release
on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: "Release Please"
    runs-on: ubuntu-22.04
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      ref: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4.1
        id: release

  trigger-build:
    name: "Trigger build"
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.release-created }}
    uses: ./.github/workflows/docker-container.yaml
    with:
      ref: ${{ needs.release-please.outputs.ref }}
